src/main/java/com/eryansky/modules/sys/entity/Log.java
/**
 *  Copyright (c) 2012-2013 http://www.eryansky.com
 *
 *  Licensed under the Apache License, Version 2.0 (the "License"); 
 */
package com.eryansky.modules.sys.entity;

import com.eryansky.common.orm.entity.BaseEntity;
import com.eryansky.modules.sys._enum.LogType;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Date;

/**
 * 系统操作日志Entity
 * @author : 尔演&Eryan eryanwcp@gmail.com
 * @date: 13-11-27 下午9:18
 */
@Entity
@Table(name = "T_SYS_LOG")
// jackson标记不生成json对象的属性
@JsonIgnoreProperties(value = {"hibernateLazyInitializer", "handler", "fieldHandler"})
public class Log extends BaseEntity implements Serializable {

    /**
     * 操作日志类型
     * @see com.eryansky.modules.sys._enum.LogType
     */
    private Integer type;
    /**
     * 登录名
     */
    private String loginName;
    /**
     * 操作开始时间
     */
    private Date operTime;
    /**
     * 模块
     */
    private String module;
    /**
     * 操作方法
     */
    private String action;
    /**
     * 操作耗时ms
     */
    private String actionTime;
    /**
     * 用户IP地址
     */
    private String ip;
    /**
     * 客户端（浏览器）类型 {@link com.eryansky.common.utils.browser.BrowserType}
     */
    private String browserType;
    /**
     * 备注
     */
    private String remark;

    public Log() {
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * 日志类类型 View
     */
    @Transient
    public String getTypeView() {
        LogType s = LogType.getLogType(type);
        String str = "";
        if(s != null){
            str =  s.getDescription();
        }
        return str;
    }

    /**
     * 登录名
     *
     * @return
     */
    @Column(length = 36)
    public String getLoginName() {
        return loginName;
    }

    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    @JsonFormat(pattern = DATE_TIME_FORMAT, timezone = TIMEZONE)
    @Temporal(TemporalType.TIMESTAMP)
    public Date getOperTime() {
        return operTime;
    }

    public void setOperTime(Date operTime) {
        this.operTime = operTime;
    }

    @Column(length = 36)
    public String getModule() {
        return module;
    }

    public void setModule(String module) {
        this.module = module;
    }

    @Column(length = 255)
    public String getAction() {
        return action;
    }

    public void setAction(String action) {
        this.action = action;
    }

    @Column(length = 20)
    public String getActionTime() {
        return actionTime;
    }

    public void setActionTime(String actionTime) {
        this.actionTime = actionTime;
    }

    @Column(length = 64)
    public String getIp() {
        return ip;
    }

    public void setIp(String ip) {
        this.ip = ip;
    }

    @Column(length = 64)
    public String getBrowserType() {
        return browserType;
    }

    public void setBrowserType(String browserType) {
        this.browserType = browserType;
    }

    @Column(length = 8192)
    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }
}

src/main/java/com/eryansky/modules/sys/entity/User.java
/**
 *  Copyright (c) 2012-2014 http://www.eryansky.com
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 */
package com.eryansky.modules.sys.entity;

import com.eryansky.common.orm.PropertyType;
import com.eryansky.common.orm.annotation.Delete;
import com.eryansky.common.orm.entity.BaseEntity;
import com.eryansky.common.utils.ConvertUtils;
import com.eryansky.common.utils.collections.Collections3;
import com.eryansky.core.security.SecurityConstants;
import com.eryansky.modules.sys._enum.SexType;
import com.fasterxml.jackson.annotation.JsonFilter;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.google.common.collect.Lists;
import org.hibernate.annotations.*;
import org.hibernate.annotations.Cache;

import javax.persistence.*;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.OrderBy;
import javax.persistence.Table;
import java.io.Serializable;
import java.util.Date;
import java.util.List;

/**
 * 用户管理User.
 * @author 尔演&Eryan eryanwcp@gmail.com
 * @date 2013-3-21 上午12:28:04 
 *
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "T_SYS_USER")
@DynamicInsert
@DynamicUpdate
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
//jackson标记不生成json对象的属性 
@JsonIgnoreProperties (value = { "hibernateLazyInitializer" , "handler","fieldHandler",
        "resources","roles","defaultOrgan","organs","posts"})
//逻辑删除注解标记 propertyName:字段名 value:删除标记的值（使用默认值"1"） type:属性类型
@Delete(propertyName = "status",type = PropertyType.I)
@JsonFilter(" ")
public class User
        extends BaseEntity
        implements Serializable {
	
    /**
     * 登录用户
     */
    private String loginName;
    /**
     * 登录密码
     */
    private String password;
    /**
     * 用户姓名
     */
    private String name;
    /**
     * 性别 女(0) 男(1) 保密(2) 默认：保密
     */
    private Integer sex = SexType.secrecy.getValue();
    /**
     * 用户出生日期
     */
    private Date birthday;

    /**
     * 头像
     */
    private String photo;


    /**
     * 邮件 以 ","分割
     */
    private String email;
    /**
     * 住址
     */
    private String address;
    /**
     * 住宅电话 以 ","分割
     */
    private String tel;
    /**
     * 手机号 以 ","分割
     */
    private String mobilephone;
    /**
     * 有序的关联对象集合
     */
    private List<Role> roles = Lists.newArrayList();
    /**
     * 有序的关联Role对象id集合
     */
    private List<Long> roleIds = Lists.newArrayList();

    /**
     * 资源 有序的关联对象集合
     */
    private List<Resource> resources = Lists.newArrayList();
    /**
     * 资源 id集合  @Transient
     */
    private List<Long> resourceIds = Lists.newArrayList();

    /**
     * 默认组织机构
     */
    private Organ defaultOrgan;
    /**
     * 默认组织机构 @Transient
     */
    private Long defaultOrganId;

    /**
     * 组织机构
     */
    private List<Organ> organs = Lists.newArrayList();

    /**
     * 组织机构ID集合 @Transient
     */
    private List<Long> organIds  = Lists.newArrayList();

    /**
     * 组织机构名称  @Transient
     */
    private String organNames;

    /**
     * 用户岗位信息
     */
    private List<Post> posts = Lists.newArrayList();
    /**
     * 排序
     */
    private Integer orderNo;
    /**
     * 备注
     */
    private String remark;

    public User() {

    }

    @Column(name = "LOGIN_NAME",length = 36, nullable = false)
    public String getLoginName() {
        return loginName;
    }

    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    @Column(name = "NAME",length = 36)
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    // 多对多定义
    @ManyToMany(cascade = {CascadeType.PERSIST, CascadeType.MERGE}, fetch = FetchType.LAZY)
    // 中间表定义,表名采用默认命名规则
    @JoinTable(name = "T_SYS_USER_ROLE", joinColumns = { @JoinColumn(name = "USER_ID") }, inverseJoinColumns = { @JoinColumn(name = "ROLE_ID") })
    // Fecth策略定义
//   @Fetch(FetchMode.SUBSELECT)
    // 集合按id排序.
    @OrderBy("id")
    @NotFound(action = NotFoundAction.IGNORE)
    @Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
    public List<Role> getRoles() {
        return roles;
    }

    public void setRoles(List<Role> roles) {
        this.roles = roles;
    }

    @Column(name = "PASSWORD",length = 64, nullable = false)
    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
    @Column(name = "SEX")
    public Integer getSex() {
        return sex;
    }

    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * 性别描述.
     */
    @Transient
    public String getSexView() {
    	SexType ss = SexType.getSexType(sex);
    	String str = "";
    	if(ss != null){
    		str = ss.getDescription();
    	}
        return str;
    }

    @JsonFormat(pattern = DATE_FORMAT, timezone = TIMEZONE)
    @Column(name = "BIRTHDAY")
    @Temporal(TemporalType.TIMESTAMP)
    public Date getBirthday() {
        return birthday;
    }

    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }


    @Column(name = "PHOTO",length = 1000)
    public String getPhoto() {
        return photo;
    }

    public void setPhoto(String photo) {
        this.photo = photo;
    }


    @Column(name = "EMAIL",length = 64)
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }
    @Column(name = "ADDRESS",length = 255)
    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }
    @Column(name = "TEL",length = 36)
    public String getTel() {
        return tel;
    }

    public void setTel(String tel) {
        this.tel = tel;
    }
    @Column(name = "MOBILEPHONE",length = 36)
    public String getMobilephone() {
        return mobilephone;
    }

    public void setMobilephone(String mobilephone) {
        this.mobilephone = mobilephone;
    }

    /**
     * 用户拥有的角色名称字符串, 多个角色名称用','分隔.
     * <br>如果是超级管理员 直接返回 "超级管理员" AppConstants.ROLE_SUPERADMIN
     */
    @Transient
    // 非持久化属性.
    public String getRoleNames() {
    	Long superId = 1L;
	    if(superId.equals(this.getId())){
	        return SecurityConstants.ROLE_SUPERADMIN;
	    }
        return ConvertUtils.convertElementPropertyToString(roles, "name",
                ", ");
    }

    @SuppressWarnings("unchecked")
    @Transient
    public List<Long> getRoleIds() {
        if (!Collections3.isEmpty(roles)) {
            roleIds = ConvertUtils.convertElementPropertyToList(roles, "id");
        }
        return roleIds;
    }

    public void setRoleIds(List<Long> roleIds) {
        this.roleIds = roleIds;
    }

    @ManyToMany(cascade = {CascadeType.PERSIST, CascadeType.MERGE}, fetch = FetchType.LAZY)
    @JoinTable(name = "T_SYS_USER_RESOURCE", joinColumns = {@JoinColumn(name = "USER_ID")},
            inverseJoinColumns = {@JoinColumn(name = "RESOURCE_ID")})
    @Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
    public List<Resource> getResources() {
        return resources;
    }

    public void setResources(List<Resource> resources) {
        this.resources = resources;
    }

    @Transient
    public List<Long> getResourceIds() {
        if (!Collections3.isEmpty(resources)) {
            resourceIds = ConvertUtils.convertElementPropertyToList(resources, "id");
        }
        return resourceIds;
    }

    public void setResourceIds(List<Long> resourceIds) {
        this.resourceIds = resourceIds;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "DEFAULT_ORGANID")
    public Organ getDefaultOrgan() {
        return defaultOrgan;
    }

    public void setDefaultOrgan(Organ defaultOrgan) {
        this.defaultOrgan = defaultOrgan;
    }

    @Transient
    public Long getDefaultOrganId() {
        if(defaultOrgan != null){
            defaultOrganId = defaultOrgan.getId();
        }
        return defaultOrganId;
    }

    public void setDefaultOrganId(Long defaultOrganId) {
        this.defaultOrganId = defaultOrganId;
    }

    @Transient
    public String getDefaultOrganName(){
        String doName = null;
        if(defaultOrgan != null){
            doName = defaultOrgan.getName();
        }
        return doName;
    }

    @Transient
    public String getDefaultOrganSysCode(){
        String sysCode = null;
        if(defaultOrgan != null){
            sysCode = defaultOrgan.getSysCode();
        }
        return sysCode;
    }

    @ManyToMany(cascade = {CascadeType.PERSIST, CascadeType.MERGE}, fetch = FetchType.LAZY)
    @JoinTable(name = "T_SYS_USER_ORGAN", joinColumns = {@JoinColumn(name = "USER_ID")},
            inverseJoinColumns = {@JoinColumn(name = "ORGAN_ID")})
    @OrderBy("sysCode asc")
    @Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
    public List<Organ> getOrgans() {
        return organs;
    }

    public void setOrgans(List<Organ> organs) {
        this.organs = organs;
    }


    @Transient
    public List<Long> getOrganIds() {
        if(!Collections3.isEmpty(organs)){
            organIds =  ConvertUtils.convertElementPropertyToList(organs, "id");
        }
        return organIds;
    }

    public void setOrganIds(List<Long> organIds) {
        this.organIds = organIds;
    }

    @Transient
    public String getOrganNames() {
        return ConvertUtils.convertElementPropertyToString(organs, "name", ", ");
    }


    @ManyToMany(cascade = {CascadeType.PERSIST, CascadeType.MERGE}, fetch = FetchType.LAZY)
    @JoinTable(name = "T_SYS_USER_POST", joinColumns = {@JoinColumn(name = "USER_ID")},
            inverseJoinColumns = {@JoinColumn(name = "POST_ID")})
    @Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
    public List<Post> getPosts() {
        return posts;
    }

    public void setPosts(List<Post> posts) {

src/main/java/com/eryansky/modules/sys/web/PortalController.java
/**
 *  Copyright (c) 2012-2014 http://www.eryansky.com
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 */
package com.eryansky.modules.sys.web;

import com.eryansky.common.model.Result;
import com.eryansky.common.web.springmvc.SimpleController;
import com.eryansky.common.web.utils.WebUtils;
import com.eryansky.core.security.SecurityUtils;
import com.eryansky.core.security.SessionInfo;
import com.eryansky.modules.notice.entity.NoticeScope;
import com.eryansky.modules.notice.service.NoticeScopeManager;
import com.eryansky.modules.sys.service.BugManager;
import com.google.common.collect.Maps;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.servlet.ModelAndView;

import javax.servlet.http.HttpServletResponse;
import java.util.*;

/**
 * Portal主页门户管理
 *
 * @author 尔演&Eryan eryanwcp@gmail.com
 * @date   2014-07-31 12:30
 */
@Controller
@RequestMapping(value = "${adminPath}/portal")
public class PortalController extends SimpleController {

    @Autowired
    private NoticeScopeManager noticeScopeManager;

    @RequestMapping("")
    public ModelAndView portal() {
        ModelAndView modelAnView = new ModelAndView("layout/portal");
        return modelAnView;
    }


    /**
     * 我的通知
     *
     * @return
     */
    @RequestMapping("notice")
    public ModelAndView notice() {
        ModelAndView modelAnView = new ModelAndView("layout/portal-notice");
        SessionInfo sessionInfo = SecurityUtils.getCurrentSessionInfo();
        if (sessionInfo != null) {
            List<NoticeScope> noticeScopes = noticeScopeManager.getUserNewNotices(sessionInfo.getUserId(), null);
            modelAnView.addObject("noticeScopes", noticeScopes);
        }

        return modelAnView;
    }

    /**
     * 个人消息中心
     *
     * @return
     * @throws Exception
     */
    @RequestMapping("mymessages")
    @ResponseBody
    public Result mymessages(HttpServletResponse response) throws Exception {
        WebUtils.setNoCacheHeader(response);
        Result result = null;
        Map<String, Long> map = Maps.newHashMap();
        // 当前登录用户
        SessionInfo sessionInfo = SecurityUtils.getCurrentSessionInfo();
        long noticeScopes = noticeScopeManager.getUserUnreadNoticeNum(sessionInfo.getUserId());
        map.put("noticeScopes", noticeScopes);

        result = Result.successResult().setObj(map);
        return result;
    }



}

src/main/webapp/WEB-INF/views/layout/app.jsp
<%@ page language="java" pageEncoding="UTF-8" contentType="text/html; charset=UTF-8" %>
<%@ include file="/common/taglibs.jsp"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>essh桌面版</title>
<%@ include file="/common/meta.jsp"%>
    <link rel="stylesheet" type="text/css" href="${ctxStatic}/js/easyui-${ev}/extend/app/app.css" />
    <script type="text/javascript" src="${ctxStatic}/js/easyui-${ev}/extend/app/jquery.app.js?_=${sysInitTime}" charset="utf-8"></script>
    <script type="text/javascript" src="${ctxStatic}/js/session-keep.js?_=${sysInitTime}" charset="utf-8"></script>
    <script type="text/javascript" src="${ctxStatic}/js/easyui-${ev}/extend/app/initApp.js?_=${sysInitTime}" charset="utf-8"></script>
    <%--<script type="text/javascript">--%>
        <%--$(function(){--%>
            <%--$.parser.parse();--%>
        <%--});--%>
    <%--</script>--%>
</head>
<body>

</body>
</html>

src/main/webapp/WEB-INF/views/layout/index.jsp
<%@ page language="java" pageEncoding="UTF-8" contentType="text/html; charset=UTF-8" %>
<%@ include file="/common/taglibs.jsp"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>后台管理主界面</title>
<%@ include file="/common/meta.jsp"%>
<script type="text/javascript" src="${ctxStatic}/js/session-keep.js" charset="utf-8"></script>
    <script type="text/javascript" charset="utf-8">
        var indexLayout;
        $(function() {
            indexLayout = $("#indexLayout").layout();
        });
    </script>
</head>
<body id="indexLayout" class="easyui-layout" style="height: 100%;width: 100%;overflow-y: hidden;">
	<noscript>
		<div style="position: absolute; z-index: 100000; height: 2046px; top: 0px; left: 0px; width: 100%; background: white; text-align: center;">
			<img src="${ctxStatic}/img/noscript.gif" alt='请开启脚本支持!' />
		</div>
	</noscript>
	<%-- north顶部Logo区域 --%>
	<div data-options="region:'north',border:false,split:false,href:'${ctxAdmin}/common/layout/north'"
		style="height: 72px;overflow: hidden;">
	</div>

	<%-- west菜单栏 --%>
	<div data-options="region:'west',title:'导航菜单',split:false,href:'${ctxAdmin}/index/west'"
		style="width: 180px;overflow: hidden;">
	</div>

	<%-- center主面板 --%>
	<div data-options="region:'center',split:false,href:'${ctxAdmin}/common/layout/center'" style="overflow: hidden;">
	</div>
	
	<%-- south底部 --%>
	<div data-options="region:'south',border:false,split:false,href:'${ctxAdmin}/common/layout/south'"
		style="height: 20px;overflow: hidden;">
	</div>
</body>
</html>

src/main/webapp/WEB-INF/views/layout/north-password.jsp
<%@ page language="java" pageEncoding="UTF-8"
	contentType="text/html; charset=UTF-8"%>
<%@ include file="/common/taglibs.jsp"%>
<div>
	<form id="login_password_form" class="dialog-form" method="post" novalidate>
		<input type="hidden" id="login_password_form_id" name="id" value="${sessionInfo.userId}" />
		<div>
			<label>原始密码:</label> <input type="password" id="password"
				name="password" class="easyui-validatebox textbox" required="true"
				missingMessage="请输入原始密码." validType="minLength[1]"/>
		</div>
		<div>
			<label>新密码:</label> <input type="password" id="newPassword"
				name="newPassword" class="easyui-validatebox textbox" required="true"
				missingMessage="请输入新密码." validType="minLength[1]" />
		</div>
		<div>
			<label>确认新密码:</label> <input type="password" name="newPassword2"
				id="newPassword2" required="true" class="easyui-validatebox textbox"
				missingMessage="请再次输入确认新密码." validType="equalTo['#newPassword']"
				invalidMessage="两次输入密码 不一致." />
		</div>
	</form>
</div>

src/main/webapp/WEB-INF/views/layout/north.jsp
<%@ page language="java" pageEncoding="UTF-8" contentType="text/html; charset=UTF-8"%>
<%@ include file="/common/taglibs.jsp"%>
<%--<script type="text/javascript" src="${ctxStatic}/app/layout/north.js?_=${sysInitTime}" charset="utf-8"></script>--%>
<div style="height: 100%;background-image: url(${ctxStatic}/img/top_bg.png); background-repeat: repeat-x;">
    <div style="float: left;">
	    <img alt="essh" title="永远的小女儿" class="easyui-tooltip" data-options="position:'right'" src="${ctxStatic}/img/essh_logo.png">
	</div>
	<%--<div style="float: right; position: absolute; bottom: 20px; right: 10px">--%>
	    <%--<div style="text-align: right;">您好,<span style="color: red;">${sessionInfo.loginName}</span>[${sessionInfo.roleNames}] 欢迎您！</div>--%>
		<%--<a href="javascript:void(0);" class="easyui-menubutton" menu="#layout_north_pfMenu" iconCls="eu-icon-user_red">更换皮肤</a>--%>
		<%--<div id="layout_north_pfMenu" style="width: 120px; display: none;">--%>
			<%--<div onclick="eu.changeTheme('bootstrap');">bootstrap</div>--%>
			<%--<div onclick="eu.changeTheme('default');">蓝色</div>--%>
			<%--<div onclick="eu.changeTheme('gray');">灰色</div>--%>
			<%--<div onclick="eu.changeTheme('black');">黑色</div>--%>
			<%--<div onclick="eu.changeTheme('metro');">metro</div>--%>
		<%--</div>--%>

	    <%--<a href="javascript:void(0);" class="easyui-menubutton" menu="#layout_north_kzmbMenu" iconCls="easyui-icon-help">控制面板</a>--%>
		<%--<div id="layout_north_kzmbMenu" style="width: 100px; display: none;">--%>
			<%--<div onclick="editLoginUserPassword();" iconCls="easyui-icon-edit">修改密码</div>--%>
			<%--<div class="menu-sep"></div>--%>
            <%--<div onclick="toApp();">切换到桌面版</div>--%>
            <%--<div class="menu-sep"></div>--%>
			<%--<div onclick="" data-options="iconCls:'easyui-icon-help'">帮助</div>--%>
			<%--<div onclick="showAbout();" data-options="iconCls:'easyui-icon-essh'">关于</div>--%>
		<%--</div>--%>

		<%--<a href="javascript:void(0);" class="easyui-menubutton" menu="#layout_north_logoutMenu" iconCls="easyui-icon-back">安全退出</a>--%>
		<%--<div id="layout_north_logoutMenu" style="width: 100px; display: none;">--%>
			<%--<div onclick="logout(true);"  data-options="iconCls:'eu-icon-lock'">切换账号</div>--%>
			<%--<div onclick="logout();"  data-options="iconCls:'eu-icon-lock'">注销</div>--%>
		<%--</div>--%>
	<%--</div>--%>
</div>

src/main/webapp/WEB-INF/views/layout/portal-about.jsp
<%@ page language="java" pageEncoding="UTF-8" contentType="text/html; charset=UTF-8"%>
<%@ include file="/common/taglibs.jsp"%>
<ul>
<li>essh是一个EasyUI整站示例系统.<br><br></li>
<li>前台由EasyUI1.3.6编写，后台是Java编写，应用框架struts2+spring3+hibernate+ehcache.<br><br></li>
<li>要求:JDk6 源码包中已提供MySQL5.1 Oracle10G的脚本.<br><br></li>
<div align="center">版权所有 &copy; 2014 <a href="mailto:eryanwcp@gmail.com">尔演&Eryan</a></div>
</ul> 

src/main/webapp/WEB-INF/views/layout/portal-notice.jsp
<%@ page language="java" pageEncoding="UTF-8" contentType="text/html; charset=UTF-8" %>
<%@ include file="/common/taglibs.jsp" %>
<script type="text/javascript">
    function viewNotice(title, id) {
        $("#notice_icon_" + id).removeClass('tree-icon tree-file eu-icon-star_yellow').addClass("tree-icon tree-file eu-icon-star_gray")
                .attr("title", "已读");
        $("#notice_label_" + id).removeClass("tip_unread").html("[已读]");
        eu.addTab(window.parent.$layout_center_tabs, "我的通知", '${ctxAdmin}/notice/notice?noticeId=' + id, true, "eu-icon-notice_user_comment", "", true);
    }
</script>
<div class="portal-div">
    <table class="table table-striped">
        <%--<thead>--%>
        <%--<tr>--%>
        <%--<th>名称</th>--%>
        <%--</tr>--%>
        <%--</thead>--%>
        <tbody>

        <c:forEach items="${noticeScopes}" begin="0" end="19" var="noticeScope">
            <c:set var="title" value="${noticeScope.title}"></c:set>
            <tr>
                <td>
                    <c:choose>
                        <c:when test="${noticeScope.isRead == 1}">
                            <span id="notice_icon_${noticeScope.id}" title="已读"
                                  class="tree-icon tree-file eu-icon-star_gray"></span>
                        </c:when>
                        <c:otherwise>
                            <span id="notice_icon_${noticeScope.id}" title="未读"
                                  class="tree-icon tree-file eu-icon-star_yellow"></span>
                        </c:otherwise>
                    </c:choose>
                        <%--<span class="tree-icon tree-file eu-icon-star_yellow"></span>--%>
                    <c:if test="${noticeScope.isTop eq '1'}"><span style="color: #FE6600;">[顶]</span></c:if>
                    <a href="#" id="notice_${noticeScope.id}" class="easyui-tooltip  portal-span" title="${title}"
                       onclick="viewNotice('${title}','${noticeScope.noticeId}')" data-options="position: 'right'">
                            ${fns:abbr(title,45)} <c:if test="${not empty noticeScope.typeView}">[${noticeScope.typeView}]</c:if><span id="notice_label_${noticeScope.id}"
                                                                                                                                       class="<c:if test="${noticeScope.isRead == 0}">tip_unread</c:if>">[${noticeScope.isReadView}]
                                                            </span>
                    </a>
                </td>
                <td align="right" class="portal-time">
                    <fmt:formatDate value="${noticeScope.publishTime }" pattern="MM-dd HH:mm"/>
                </td>
            </tr>
        </c:forEach>
        </tbody>
    </table>
    <%--<div style="float: right;margin-right: 4px;">--%>
    <%--<button class="btn btn-primary" onclick="eu.addTab(window.parent.$layout_center_tabs,'我的通知','${ctxAdmin}/notice/notice?mode=view',true)" type="button">更 多</button>--%>
    <%--</div>--%>
</div>