src/main/java/com/eryansky/modules/disk/entity/File.java
package com.eryansky.modules.disk.entity;

import com.eryansky.common.orm.entity.BaseEntity;
import com.eryansky.common.utils.PrettyMemoryUtils;
import com.fasterxml.jackson.annotation.JsonFilter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.eryansky.modules.disk.entity._enum.FileType;
import com.eryansky.modules.sys.utils.UserUtils;
import com.eryansky.utils.AppConstants;

import javax.persistence.*;
import java.io.Serializable;

/**
 * 文件
 */
@Entity
@Table(name = "T_DISK_FILE")
// jackson标记不生成json对象的属性
@JsonIgnoreProperties(value = {"hibernateLazyInitializer", "handler", "fieldHandler",
        "folder"})
@JsonFilter(" ")
//@Delete(propertyName = "status", type = PropertyType.I)
@SuppressWarnings("serial")
public class File extends BaseEntity implements Serializable {

    /**
     * 文件名
     */
    private String name;

    /**
     * 文件标识 用户ID + "_" + hex(md5(filename + now nano time + counter++))
     * ${@link com.eryansky.core.web.upload.FileUploadUtils.encodingFilenamePrefix}
     * 区别于文件的md5
     */
    private String code;
    /**
     * 存储路径
     */
    private String filePath;

    /**
     * 文件大小 单位 字节
     */
    private Long fileSize;
    /**
     * 文件后缀
     */
    private String fileSuffix;
    /**
     * 关键字
     */
    private String keyword;
    /**
     * 备注
     */
    private String remark;
    /**
     * 文件分类 {@link com.eryansky.modules.disk.entity._enum.FileType}
     */
    private Integer fileType = FileType.Other.getValue();
    /**
     * 所属文件夹
     */
    private Folder folder;
    /**
     * 所属用户
     */
    private Long userId;
    /**
     * 分享用户 从该用户分享文件
     */
    private Long shareUserId;


    /**
     * 构造方法
     */
    public File() {
    }

    @Column(name = "NAME", length = 512,nullable = false)
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }


    @Column(length = 128,nullable = false)
    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public Long getFileSize() {
        return fileSize;
    }

    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }

    @Column(length = 4096)
    public String getFilePath() {
        return filePath;
    }

    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    @Column(length = 36)
    public String getFileSuffix() {
        return fileSuffix;
    }

    public void setFileSuffix(String fileSuffix) {
        this.fileSuffix = fileSuffix;
    }


    @Column(length = 256)
    public String getKeyword() {
        return keyword;
    }

    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }

    @Column(length = 256)
    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public Integer getFileType() {
        return fileType;
    }

    public void setFileType(Integer fileType) {
        this.fileType = fileType;
    }

    @ManyToOne(cascade = {CascadeType.PERSIST, CascadeType.MERGE})
    @JoinColumn(name = "FOLDER_ID")
    public Folder getFolder() {
        return folder;
    }

    public void setFolder(Folder folder) {
        this.folder = folder;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Long getShareUserId() {
        return shareUserId;
    }

    public void setShareUserId(Long shareUserId) {
        this.shareUserId = shareUserId;
    }

    @Transient
    public String getUserName(){
        return UserUtils.getUserName(userId);
    }

    @Transient
    public String getPrettyFileSize() {
        return PrettyMemoryUtils.prettyByteSize(fileSize);
    }


    /**
     * 文件复制
     * @return
     */
    public File copy(){
        File f = new File();
        f.setName(this.getName());
        f.setFilePath(this.filePath);
        f.setCode(this.getCode());
        f.setFileSuffix(this.getFileSuffix());
        f.setFileSize(this.getFileSize());
        f.setFileType(this.getFileType());
        f.setKeyword(this.getKeyword());
        f.setRemark(this.getRemark());
        f.setShareUserId(this.getUserId());
        return f;
    }

    /**
     * 获取对应磁盘文件
     * @return
     */
    @Transient
    public java.io.File getDiskFile(){
        return new java.io.File(AppConstants.getDiskBasePath()+java.io.File.separator+this.getFilePath());
    }
}

src/main/java/com/eryansky/modules/disk/entity/Folder.java
package com.eryansky.modules.disk.entity;

import com.eryansky.common.orm.PropertyType;
import com.eryansky.common.orm.annotation.Delete;
import com.eryansky.common.orm.entity.BaseEntity;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.eryansky.modules.disk.entity._enum.FolderAuthorize;
import com.eryansky.modules.sys.utils.UserUtils;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Transient;
import java.io.Serializable;


/**
 * 文件夹
 */
@Entity
@Table(name = "T_DISK_FOLDER")
// jackson标记不生成json对象的属性
@JsonIgnoreProperties(value = {"hibernateLazyInitializer", "handler", "fieldHandler",
        "parentFolder", "subFolders"})
@Delete(propertyName = "status", type = PropertyType.I)
@SuppressWarnings("serial")
public class Folder extends BaseEntity implements Serializable {
    /**
     * 名称
     */
    private String name;
    /**
     * 存储路径
     */
    private String path;
    /**
     * 大小限制  单位：M 无限制：0
     */
    private Integer limitSize;
    /**
     * 备注
     */
    private String remark;
    /**
     * 排序
     */
    private Integer orderNo;

    /**
     * 授权 {@link com.eryansky.modules.disk.entity._enum.FolderAuthorize}
     */
    private Integer folderAuthorize = FolderAuthorize.User.getValue();
    /**
     * 文件夹标识 授权类型为System时使用
     */
    private String code;
    /**
     * 所属用户
     */
    private Long userId;
    /**
     * 所属部门
     */
    private Long organId;
    /**
     * 授权角色
     */
    private Long roleId;

    /**
     * 父级ID
     */
    private Long parentId;

    /**
     * 构造方法
     */
    public Folder() {
    }

    @Column(name = "NAME", length = 255)
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }


    public Integer getLimitSize() {
        return limitSize;
    }

    public void setLimitSize(Integer limitSize) {
        this.limitSize = limitSize;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    @Column(name = "FOLDER_AUTHORIZE")
    public Integer getFolderAuthorize() {
        return folderAuthorize;
    }

    public void setFolderAuthorize(Integer folderAuthorize) {
        this.folderAuthorize = folderAuthorize;
    }

    @Column(name = "CODE", length = 36)
    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    @Column(name = "REMARK", length = 255)
    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public Long getUserId() {
        return userId;
    }

    public Integer getOrderNo() {
        return orderNo;
    }

    public void setOrderNo(Integer orderNo) {
        this.orderNo = orderNo;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Long getOrganId() {
        return organId;
    }

    public void setOrganId(Long organId) {
        this.organId = organId;
    }

    public Long getRoleId() {
        return roleId;
    }

    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    @Column
    public Long getParentId() {
        return parentId;
    }

    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    @Transient
    public String getUserName(){
        return UserUtils.getUserName(userId);
    }
}

src/main/java/com/eryansky/modules/disk/entity/OrganStorage.java
/**
 *  Copyright (c) 2014 http://www.jfit.com.cn
 *
 *          江西省锦峰软件科技有限公司
 */
package com.eryansky.modules.disk.entity;

import com.eryansky.common.orm.entity.AutoEntity;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.eryansky.utils.AppConstants;

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * 部门云盘存储空间配置
 * @author 温春平@wencp wencp@jx.tobacco.gov.cn
 * @date 2014-11-24
 */
@Entity
@Table(name = "T_DISK_ORGAN_STORAGE")
@JsonIgnoreProperties(value = {"hibernateLazyInitializer", "handler", "fieldHandler"})
public class OrganStorage extends AutoEntity {

    /**
     * 部门ID
     */
    private Long organId;
    /**
     * 最大限制大小 单位：M {@link com.eryansky.utils.AppConstants}
     */
    private Integer limitSize = AppConstants.getDiskOrganLimitSize();

    public OrganStorage(Long organId) {
        this.organId = organId;
    }

    public Long getOrganId() {
        return organId;
    }

    public void setOrganId(Long organId) {
        this.organId = organId;
    }

    public Integer getLimitSize() {
        return limitSize;
    }

    public void setLimitSize(Integer limitSize) {
        this.limitSize = limitSize;
    }
}

src/main/java/com/eryansky/modules/notice/entity/Notice.java
/**
 *  Copyright (c) 2013-2014 http://www.jfit.com.cn
 *
 *          江西省锦峰软件科技有限公司         
 */
package com.eryansky.modules.notice.entity;

import com.eryansky.common.orm.entity.BaseEntity;
import com.fasterxml.jackson.annotation.JsonFilter;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.eryansky.modules.notice._enum.IsTop;
import com.eryansky.modules.notice._enum.NoticeMode;
import com.eryansky.modules.notice.entity.common.INotice;
import com.eryansky.modules.notice.utils.NoticeUtils;
import com.eryansky.modules.sys.utils.DictionaryUtils;
import com.eryansky.modules.sys.utils.OrganUtils;
import com.eryansky.modules.sys.utils.UserUtils;
import com.eryansky.utils.YesOrNo;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;

/**
 * 内部通知 实体类
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "t_notice_notice")
@JsonIgnoreProperties(value = {"hibernateLazyInitializer", "handler", "fieldHandler"})
@JsonFilter(" ")
public class Notice extends BaseEntity implements INotice {

    public static final String DATE_TIME_SHORT_FORMAT = "yyyy-MM-dd HH:mm";

    /**
     * 通知公告标题
     */
    private String title;
    /**
     * 通知公告类型 {@DictionaryUtils.DIC_NOTICE}
     */
    private String type;
    /**
     * 通知公告内容
     */
    private String content;
    /**
     * 附件
     */
    private List<Long> fileIds = new ArrayList<Long>(0);


    /**
     * 发布人
     */
    private Long userId;
    /**
     * 发布部门
     */
    private Long organId;


    /**
     * 0表示不置顶，1表示置顶
     */
    private Integer isTop;
    /**
     * 结束置顶天数
     */
    private Integer endTopDay;

    /**
     * 状态 默认：未发布 {@link com.eryansky.modules.notice._enum.NoticeMode}
     */
    private Integer noticeMode = NoticeMode.UnPublish.getValue();
    /**
     * 发布日期
     */
    private Date publishTime;

    /**
     * 生效时间
     */
    private Date effectTime = Calendar.getInstance().getTime();
    /**
     * 失效时间 为空，则一直有效
     */
    private Date endTime;
    /**
     * 是否记录 查看情况
     */
    private Integer isRecordRead = YesOrNo.YES.getValue();

    /**
     * 是否发给所有人，否则需要指定接收人或部门 默认值：是
     */
    private Integer isToAll = YesOrNo.YES.getValue();

    /**
     * 接收人
     */
    private List<Long> noticeUserIds = new ArrayList<Long>(0);
    /**
     * 接收部门
     */
    private List<Long> noticeOrganIds = new ArrayList<Long>(0);


    public void setTitle(String title) {
        this.title = title;
    }

    @Column(length = 512)
    public String getTitle() {
        return this.title;
    }

    @Column(length = 36)
    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public void setContent(String content) {
        this.content = content;
    }

    @JsonIgnore
    @Column(length = 4096)
    public String getContent() {
        return this.content;
    }


    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Long getOrganId() {
        return organId;
    }

    public void setOrganId(Long organId) {
        this.organId = organId;
    }


    public void setIsTop(Integer isTop) {
        this.isTop = isTop;
    }

    public Integer getIsTop() {
        return this.isTop;
    }

    public void setEndTopDay(Integer endTopDay) {
        this.endTopDay = endTopDay;
    }

    public Integer getEndTopDay() {
        return this.endTopDay;
    }



    public void setNoticeMode(Integer noticeMode) {
        this.noticeMode = noticeMode;
    }

    public Integer getNoticeMode() {
        return this.noticeMode;
    }

    @JsonFormat(pattern = DATE_TIME_FORMAT, timezone = TIMEZONE)
    @Temporal(TemporalType.TIMESTAMP)
    public Date getPublishTime() {
        return publishTime;
    }


    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }


    public void setEffectTime(Date effectTime) {
        this.effectTime = effectTime;
    }

    @JsonFormat(pattern = DATE_TIME_SHORT_FORMAT, timezone = TIMEZONE)
    @Temporal(TemporalType.TIMESTAMP)
    public Date getEffectTime() {
        return this.effectTime;
    }

    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    @JsonFormat(pattern = DATE_TIME_SHORT_FORMAT, timezone = TIMEZONE)
    @Temporal(TemporalType.TIMESTAMP)
    public Date getEndTime() {
        return this.endTime;
    }

    public Integer getIsRecordRead() {
        return isRecordRead;
    }

    public void setIsRecordRead(Integer isRecordRead) {
        this.isRecordRead = isRecordRead;
    }

    public Integer getIsToAll() {
        return isToAll;
    }

    public void setIsToAll(Integer isToAll) {
        this.isToAll = isToAll;
    }


    @JsonIgnore
    @ElementCollection
    @CollectionTable(name = "T_NOTICE_NOTICE_FILE", joinColumns = {@JoinColumn(name = "NOTICE_ID")})
    @Column(name = "FILE_ID")
    public List<Long> getFileIds() {
        return fileIds;
    }

    public void setFileIds(List<Long> fileIds) {
        this.fileIds = fileIds;
    }

    @JsonIgnore
    @ElementCollection
    @CollectionTable(name = "T_NOTICE_NOTICE_ORGAN", joinColumns = {@JoinColumn(name = "NOTICE_ID")})
    @Column(name = "ORGAN_ID")
    public List<Long> getNoticeOrganIds() {
        return noticeOrganIds;
    }

    public void setNoticeOrganIds(List<Long> noticeOrganIds) {
        this.noticeOrganIds = noticeOrganIds;
    }


    @ElementCollection
    @CollectionTable(name = "T_NOTICE_NOTICE_USER", joinColumns = {@JoinColumn(name = "NOTICE_ID")})
    @Column(name = "USER_ID")
    public List<Long> getNoticeUserIds() {
        return noticeUserIds;
    }

    public void setNoticeUserIds(List<Long> noticeUserIds) {
        this.noticeUserIds = noticeUserIds;
    }


    /**
     * 通知类型 由数据字典转换而来
     *
     * @return
     */
    @Transient
    public String getTypeView() {
        return DictionaryUtils.getDictionaryNameByDV(NoticeUtils.DIC_NOTICE, this.getType(), this.getType());
    }

    @Transient
    @Override
    public String getIsTopView() {
        IsTop s = IsTop.getIsTop(noticeMode);
        String str = "";
        if(s != null){
            str =  s.getDescription();
        }
        return str;
    }

    @Transient
    @Override
    public String getNoticeModeView() {
        NoticeMode s = NoticeMode.getNoticeMode(noticeMode);
        String str = "";
        if(s != null){
            str =  s.getDescription();
        }
        return str;
    }

    /**
     * 是否发布 显示 {@link com.jfit.modules.notice._enum.NoticeMode}
     *
     * @return
     */
    @Transient
    public String getIsPublishView() {
        if (noticeMode != null) {
            return NoticeMode.getNoticeMode(noticeMode).getDescription();
        }
        return null;
    }

    /**
     * 发布人姓名
     * @return
     */
    @Transient
    public String getPublishUserName(){
        return UserUtils.getUserName(this.userId);
    }

    /**
     * 发布部门 名称
     * @return
     */
    @Transient
    public String getPublishOrganName(){
        return OrganUtils.getOrganName(this.organId);
    }

    /**
     * 通知接收人员
     *
     * @return
     */
    @Transient
    public String getNoticeUserNames() {
        return UserUtils.getUserNames(this.noticeUserIds);
    }

    /**
     * 通知接收部门
     *
     * @return
     */
    @Transient
    public String getNoticeOrganNames() {
        return OrganUtils.getOrganNames(this.noticeOrganIds);
    }

    /**
     * 通知ID
     * @return
     */
    @Transient
    public Long getNoticeId() {
        return this.id;
    }

    /**
     * 转发
     * @return
     */
    @Transient
    public Notice repeat() {
        Notice notice = new Notice();
        notice.setTitle(NoticeUtils.MSG_REPEAT + this.getTitle());
        notice.setContent(this.getContent());
        notice.setType(this.getType());
        notice.setIsTop(this.getIsTop());
        notice.setEndTopDay(this.getEndTopDay());
        notice.setEffectTime(this.getEffectTime());
        notice.setEndTopDay(this.getEndTopDay());
        return notice;
    }

}

src/main/webapp/WEB-INF/views/modules/notice/notice-readInfo.jsp
<%@ page language="java" pageEncoding="UTF-8" contentType="text/html; charset=UTF-8" %>
<%@ include file="/common/taglibs.jsp" %>
<script type="text/javascript">
    $(function() {
        $('#notice_readInfo_datagrid').datagrid({
                    url : '${ctxAdmin}/notice/notice/readInfoDatagrid/${noticeId}',
                    fit:true,
                    pagination:true,//底部分页
                    rownumbers:true,//显示行数
                    fitColumns:false,//自适应列宽
                    striped:true,//显示条纹
                    nowrap : true,
                    pageSize:20,//每页记录数
                    remoteSort:false,//是否通过远程服务器对数据排序
                    sortName:'id',//默认排序字段
                    sortOrder:'asc',//默认排序方式 'desc' 'asc'
                    idField : 'id',
                    columns : [ [
                        {field:'id',title:'主键',hidden:true,sortable:true,align:'right',width:80},
                        {field : 'userName',
                            title : '姓名',
                            width : 80
                        }, {
                            field : 'organName',
                            title : '部门',
                            width : 200
                        },{
                            field : 'isReadView',
                            title : '状态',
                            width : 60
                        }]],
                    queryParams: {
                        noticeId: '${noticeId}'
                    }
                }).datagrid('showTooltip');



    });

</script>
<table id="notice_readInfo_datagrid"></table>

src/main/webapp/WEB-INF/views/modules/notice/notice-view.jsp
<%@ page language="java" pageEncoding="UTF-8"
         contentType="text/html; charset=UTF-8"%>
<%@ include file="/common/taglibs.jsp"%>
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=EDGE;chrome=1" />
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
    <meta http-equiv="Cache-Control" content="no-store"/>
    <meta http-equiv="Pragma" content="no-cache"/>
    <meta http-equiv="Expires" content="0"/>
    <title>${model.title}</title>

    <script type="text/javascript">
	    function init() {
	        var parentDIv = window.parent.document.getElementById("notice_view_iframe");
	        var contentY = document.getElementById("content");
	        if (parentDIv) {
	            parentDIv.style.height = document.body.clientHeight + "px";
	            var panelWidth = parseInt(parentDIv.parentNode.style.width);
	            var contentWidth = contentY.clientWidth + 60;
	            var setWidth = (contentWidth > panelWidth ? contentWidth: panelWidth);
	            parentDIv.style.width = setWidth + "px";
	            contentY.style.width = (setWidth - 200) + "px";
	
	        }
	        //修复Chrome浏览器不显示 border小于0.75pt的边框问题
	        var tdDoms = document.getElementsByTagName("td");
	        if (tdDoms) {
	            for (var i = 0; i < tdDoms.length; i++) {
	                var border = tdDoms[i].style.border;
	                if (border && border.indexOf("0.5pt") == 0) {
	                    tdDoms[i].style.border = border.replace("0.5pt", "0.75pt");
	                }
	            }
	        }
	    }
        function _download(fileId) {
            var annexFrame = document.getElementById("annexFrame");
            annexFrame.src = '${ctxAdmin}/disk/fileDownload/' + fileId;
        }
    </script>
</head>
<body onload="init();" style="overflow: hidden;margin: 0px;">
<div style="padding: 0px 60px 0px 30px;">
    <div style="width:100%;float: left;margin-top:10px;margin-bottom:10px;padding: 8px 15px 8px;background-color: #f5f5f5;border-top:2px solid #000;border-bottom:2px solid #000;">
        <div align="center">
            <h3>${model.title}</h3>
        </div>
        <div align="right">
            [ <label>发布部门：</label>${model.publishOrganName}&nbsp;&nbsp;<label>发布人：</label>${model.publishUserName}&nbsp;&nbsp;<label>发布时间：</label><fmt:formatDate value="${model.publishTime}" pattern='yyyy-MM-dd HH:mm' />]
        </div>
    </div>
    <div id="content" style="float: left;">
        ${model.content}
        <%--<iframe id="notice_content_iframe"  scrolling="no" frameborder="0"  src="${ctxAdmin}/notice/notice/notice?id=${model.id}" style="height:100%; width:100%; overflow:hidden;"></iframe>--%>
    </div>
    <br/>
    <c:if test="${not empty files}">
        <div style="float: left;width:100%;border-top:1px solid #000;padding-top:10px;margin-top:10px;">
            <strong>附件列表：</strong>
            <br/>
            <c:forEach items="${files}" begin="0" var="file" varStatus="i">
                <div style="margin-top: 10px;">${i.index +1}、<a href="javascript:void(0)" onclick="javascript:_download('${file.id}');">${file.name}</a></div>
            </c:forEach>
        </div>
    </c:if>
    <iframe id="annexFrame" src="" frameborder="no" style="padding: 0;border: 0;width: 100%;height: 50px;"></iframe>
</div>
</body>
</html>