src/main/java/com/eryansky/modules/disk/entity/File.java
package com.eryansky.modules.disk.entity;

import com.eryansky.common.orm.entity.BaseEntity;
import com.eryansky.common.utils.PrettyMemoryUtils;
import com.fasterxml.jackson.annotation.JsonFilter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.eryansky.modules.disk.entity._enum.FileType;
import com.eryansky.modules.sys.utils.UserUtils;
import com.eryansky.utils.AppConstants;

import javax.persistence.*;
import java.io.Serializable;

/**
 * 文件
 */
@Entity
@Table(name = "T_DISK_FILE")
// jackson标记不生成json对象的属性
@JsonIgnoreProperties(value = {"hibernateLazyInitializer", "handler", "fieldHandler",
        "folder"})
@JsonFilter(" ")
//@Delete(propertyName = "status", type = PropertyType.I)
@SuppressWarnings("serial")
public class File extends BaseEntity implements Serializable {

    /**
     * 文件名
     */
    private String name;

    /**
     * 文件标识 用户ID + "_" + hex(md5(filename + now nano time + counter++))
     * ${@link com.eryansky.core.web.upload.FileUploadUtils.encodingFilenamePrefix}
     * 区别于文件的md5
     */
    private String code;
    /**
     * 存储路径
     */
    private String filePath;

    /**
     * 文件大小 单位 字节
     */
    private Long fileSize;
    /**
     * 文件后缀
     */
    private String fileSuffix;
    /**
     * 关键字
     */
    private String keyword;
    /**
     * 备注
     */
    private String remark;
    /**
     * 文件分类 {@link com.eryansky.modules.disk.entity._enum.FileType}
     */
    private Integer fileType = FileType.Other.getValue();
    /**
     * 所属文件夹
     */
    private Folder folder;
    /**
     * 所属用户
     */
    private Long userId;
    /**
     * 分享用户 从该用户分享文件
     */
    private Long shareUserId;


    /**
     * 构造方法
     */
    public File() {
    }

    @Column(name = "NAME", length = 512,nullable = false)
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }


    @Column(length = 128,nullable = false)
    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public Long getFileSize() {
        return fileSize;
    }

    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }

    @Column(length = 4096)
    public String getFilePath() {
        return filePath;
    }

    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    @Column(length = 36)
    public String getFileSuffix() {
        return fileSuffix;
    }

    public void setFileSuffix(String fileSuffix) {
        this.fileSuffix = fileSuffix;
    }


    @Column(length = 256)
    public String getKeyword() {
        return keyword;
    }

    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }

    @Column(length = 256)
    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public Integer getFileType() {
        return fileType;
    }

    public void setFileType(Integer fileType) {
        this.fileType = fileType;
    }

    @ManyToOne(cascade = {CascadeType.PERSIST, CascadeType.MERGE})
    @JoinColumn(name = "FOLDER_ID")
    public Folder getFolder() {
        return folder;
    }

    public void setFolder(Folder folder) {
        this.folder = folder;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Long getShareUserId() {
        return shareUserId;
    }

    public void setShareUserId(Long shareUserId) {
        this.shareUserId = shareUserId;
    }

    @Transient
    public String getUserName(){
        return UserUtils.getUserName(userId);
    }

    @Transient
    public String getPrettyFileSize() {
        return PrettyMemoryUtils.prettyByteSize(fileSize);
    }


    /**
     * 文件复制
     * @return
     */
    public File copy(){
        File f = new File();
        f.setName(this.getName());
        f.setFilePath(this.filePath);
        f.setCode(this.getCode());
        f.setFileSuffix(this.getFileSuffix());
        f.setFileSize(this.getFileSize());
        f.setFileType(this.getFileType());
        f.setKeyword(this.getKeyword());
        f.setRemark(this.getRemark());
        f.setShareUserId(this.getUserId());
        return f;
    }

    /**
     * 获取对应磁盘文件
     * @return
     */
    @Transient
    public java.io.File getDiskFile(){
        return new java.io.File(AppConstants.getDiskBasePath()+java.io.File.separator+this.getFilePath());
    }
}

src/main/java/com/eryansky/modules/disk/entity/Folder.java
package com.eryansky.modules.disk.entity;

import com.eryansky.common.orm.PropertyType;
import com.eryansky.common.orm.annotation.Delete;
import com.eryansky.common.orm.entity.BaseEntity;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.eryansky.modules.disk.entity._enum.FolderAuthorize;
import com.eryansky.modules.sys.utils.UserUtils;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Transient;
import java.io.Serializable;


/**
 * 文件夹
 */
@Entity
@Table(name = "T_DISK_FOLDER")
// jackson标记不生成json对象的属性
@JsonIgnoreProperties(value = {"hibernateLazyInitializer", "handler", "fieldHandler",
        "parentFolder", "subFolders"})
@Delete(propertyName = "status", type = PropertyType.I)
@SuppressWarnings("serial")
public class Folder extends BaseEntity implements Serializable {
    /**
     * 名称
     */
    private String name;
    /**
     * 存储路径
     */
    private String path;
    /**
     * 大小限制  单位：M 无限制：0
     */
    private Integer limitSize;
    /**
     * 备注
     */
    private String remark;
    /**
     * 排序
     */
    private Integer orderNo;

    /**
     * 授权 {@link com.eryansky.modules.disk.entity._enum.FolderAuthorize}
     */
    private Integer folderAuthorize = FolderAuthorize.User.getValue();
    /**
     * 文件夹标识 授权类型为System时使用
     */
    private String code;
    /**
     * 所属用户
     */
    private Long userId;
    /**
     * 所属部门
     */
    private Long organId;
    /**
     * 授权角色
     */
    private Long roleId;

    /**
     * 父级ID
     */
    private Long parentId;

    /**
     * 构造方法
     */
    public Folder() {
    }

    @Column(name = "NAME", length = 255)
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }


    public Integer getLimitSize() {
        return limitSize;
    }

    public void setLimitSize(Integer limitSize) {
        this.limitSize = limitSize;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    @Column(name = "FOLDER_AUTHORIZE")
    public Integer getFolderAuthorize() {
        return folderAuthorize;
    }

    public void setFolderAuthorize(Integer folderAuthorize) {
        this.folderAuthorize = folderAuthorize;
    }

    @Column(name = "CODE", length = 36)
    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    @Column(name = "REMARK", length = 255)
    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public Long getUserId() {
        return userId;
    }

    public Integer getOrderNo() {
        return orderNo;
    }

    public void setOrderNo(Integer orderNo) {
        this.orderNo = orderNo;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Long getOrganId() {
        return organId;
    }

    public void setOrganId(Long organId) {
        this.organId = organId;
    }

    public Long getRoleId() {
        return roleId;
    }

    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    @Column
    public Long getParentId() {
        return parentId;
    }

    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    @Transient
    public String getUserName(){
        return UserUtils.getUserName(userId);
    }
}

src/main/java/com/eryansky/modules/disk/entity/OrganStorage.java
/**
 *  Copyright (c) 2014 http://www.jfit.com.cn
 *
 *          江西省锦峰软件科技有限公司
 */
package com.eryansky.modules.disk.entity;

import com.eryansky.common.orm.entity.AutoEntity;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.eryansky.utils.AppConstants;

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * 部门云盘存储空间配置
 * @author 温春平@wencp wencp@jx.tobacco.gov.cn
 * @date 2014-11-24
 */
@Entity
@Table(name = "T_DISK_ORGAN_STORAGE")
@JsonIgnoreProperties(value = {"hibernateLazyInitializer", "handler", "fieldHandler"})
public class OrganStorage extends AutoEntity {

    /**
     * 部门ID
     */
    private Long organId;
    /**
     * 最大限制大小 单位：M {@link com.eryansky.utils.AppConstants}
     */
    private Integer limitSize = AppConstants.getDiskOrganLimitSize();

    public OrganStorage(Long organId) {
        this.organId = organId;
    }

    public Long getOrganId() {
        return organId;
    }

    public void setOrganId(Long organId) {
        this.organId = organId;
    }

    public Integer getLimitSize() {
        return limitSize;
    }

    public void setLimitSize(Integer limitSize) {
        this.limitSize = limitSize;
    }
}

src/main/java/com/eryansky/modules/disk/entity/UserStorage.java
/**
 *  Copyright (c) 2014 http://www.jfit.com.cn
 *
 *          江西省锦峰软件科技有限公司
 */
package com.eryansky.modules.disk.entity;

import com.eryansky.common.orm.entity.AutoEntity;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.eryansky.utils.AppConstants;

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * 用户云盘存储空间配置
 * @author 温春平@wencp wencp@jx.tobacco.gov.cn
 * @date 2014-11-24
 */
@Entity
@Table(name = "T_DISK_USER_STORAGE")
@JsonIgnoreProperties(value = {"hibernateLazyInitializer", "handler", "fieldHandler"})
public class UserStorage extends AutoEntity {

    /**
     * 用户ID
     */
    private Long userId;
    /**
     * 最大限制大小 单位：M {@link com.eryansky.utils.AppConstants}
     */
    private Integer limitSize = AppConstants.getDiskUserLimitSize();

    public UserStorage(Long userId) {
        this.userId = userId;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Integer getLimitSize() {
        return limitSize;
    }

    public void setLimitSize(Integer limitSize) {
        this.limitSize = limitSize;
    }
}

src/main/java/com/eryansky/modules/disk/entity/_enum/FileType.java
package com.eryansky.modules.disk.entity._enum;


import com.eryansky.common.utils.StringUtils;

/**
 * 文件类型
 */
public enum FileType {
    /**
     * 文档(0)
     */
    Document(0, "文档"),
    /**
     * 图片(1)
     */
    Image(1, "图片"),
    /**
     * 媒体(2)
     */
    Music(2, "音乐"),
    /**
     * 媒体(2)
     */
    Video(2, "视频"),
    /**
     * 软件(3)
     */
    Soft(3, "软件"),
    /**
     * 其它(4)
     */
    Other(4, "其它");

    /**
     * 值 Integer型
     */
    private final Integer value;
    /**
     * 描述 String型
     */
    private final String description;

    FileType(Integer value, String description) {
        this.value = value;
        this.description = description;
    }

    /**
     * 获取值
     *
     * @return value
     */
    public Integer getValue() {
        return value;
    }

    /**
     * 获取描述信息
     *
     * @return description
     */
    public String getDescription() {
        return description;
    }

    public static FileType getFileType(Integer value) {
        if (null == value)
            return null;
        for (FileType _enum : FileType.values()) {
            if (value.equals(_enum.getValue()))
                return _enum;
        }
        return null;
    }

    public static FileType getFileType(String description) {
        if (null == description)
            return null;
        for (FileType _enum : FileType.values()) {
            if (description.equals(_enum.getDescription()))
                return _enum;
        }
        return null;
    }

    /**
     * 根据文件后缀名返回文件分类
     * @param fileSuffix
     * @return
     */
    public static FileType getFileTypeByFileSuffix(String fileSuffix) {
        FileType fileType = FileType.Other;
        if (StringUtils.isNotBlank(fileSuffix)){
            //TODO
        }
        return fileType;
    }
}

src/main/java/com/eryansky/modules/disk/entity/_enum/FolderAuthorize.java
package com.eryansky.modules.disk.entity._enum;


/**
 * 文件夹授权
 */
public enum FolderAuthorize {
    /**
     * 个人(0)
     */
    User(0, "我的云盘"),
    /**
     * 系统(1)
     */
    SysTem(1, "系统云盘"),
    /**
     * 部门(2)
     */
    Organ(2, "部门云盘"),
    /**
     * 角色(3)
     */
    Role(3, "角色云盘"),
    /**
     * 公开(4)
     */
    Pulic(4, "公共云盘");

    /**
     * 值 Integer型
     */
    private final Integer value;
    /**
     * 描述 String型
     */
    private final String description;

    FolderAuthorize(Integer value, String description) {
        this.value = value;
        this.description = description;
    }

    /**
     * 获取值
     *
     * @return value
     */
    public Integer getValue() {
        return value;
    }

    /**
     * 获取描述信息
     *
     * @return description
     */
    public String getDescription() {
        return description;
    }

    public static FolderAuthorize getFolderAuthorize(Integer value) {
        if (null == value)
            return null;
        for (FolderAuthorize _enum : FolderAuthorize.values()) {
            if (value.equals(_enum.getValue()))
                return _enum;
        }
        return null;
    }

    public static FolderAuthorize getFolderAuthorize(String description) {
        if (null == description)
            return null;
        for (FolderAuthorize _enum : FolderAuthorize.values()) {
            if (description.equals(_enum.getDescription()))
                return _enum;
        }
        return null;
    }
}

src/main/java/com/eryansky/modules/notice/entity/common/BaseReferenceNotice.java
/**
 *  Copyright (c) 2012-2014 http://www.eryansky.com
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 */
package com.eryansky.modules.notice.entity.common;

import com.eryansky.common.orm.entity.AutoEntity;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.eryansky.modules.notice._enum.NoticeReadMode;
import com.eryansky.modules.notice.entity.Notice;
import com.eryansky.modules.notice.utils.NoticeUtils;

import javax.persistence.MappedSuperclass;
import javax.persistence.Transient;
import java.util.Date;

/**
 * @author 尔演&Eryan eryanwcp@gmail.com
 * @date 2015-01-30
 */
@MappedSuperclass
public class BaseReferenceNotice extends AutoEntity implements INotice {

    private Long noticeId;

    private Notice notice;

    /**
     * 带缓存查询
     * @return
     */
    @JsonIgnore
    @Transient
    public Notice getNotice() {
        if(this.notice == null){
            this.notice = NoticeUtils.getNotice(noticeId);
        }
        return notice;
    }

    public Long getNoticeId() {
        return noticeId;
    }

    public void setNoticeId(Long noticeId) {
        this.noticeId = noticeId;
    }

    @Transient
    @Override
    public String getTitle() {
        return getNotice().getTitle();
    }

    @Transient
    @Override
    public String getType() {
        return getNotice().getType();
    }

    @Transient
    @Override
    public String getTypeView() {
        return getNotice().getTypeView();
    }

    @Transient
    @Override
    public String getContent() {
        return getNotice().getContent();
    }

    @Transient
    @Override
    public String getPublishUserName() {
        return getNotice().getPublishUserName();
    }

    @Transient
    @Override
    public String getPublishOrganName() {
        return getNotice().getPublishOrganName();
    }

    @Transient
    @Override
    public Date getPublishTime() {
        return getNotice().getPublishTime();
    }

    @Transient
    @Override
    public Integer getIsTop() {
        return getNotice().getIsTop();
    }

    @Transient
    @Override
    public String getIsTopView() {
        return getNotice().getIsTopView();
    }

    @Transient
    @Override
    public String getNoticeModeView() {
        return getNotice().getNoticeModeView();
    }



    /**
     * 判断当前登录用户是否读取
     * @return
     */
    @Transient
    public boolean isRead(){
        return NoticeUtils.isRead(this.noticeId);
    }

    /**
     * 判断当前登录用户是否读取
     * @return
     */
    @Transient
    public String isReadView(){
        return this.isRead() == true ? NoticeReadMode.readed.getDescription():NoticeReadMode.unreaded.getDescription();
    }
}

src/main/java/com/eryansky/modules/notice/entity/common/INotice.java
package com.eryansky.modules.notice.entity.common;

import java.util.Date;

/**
 * Copyright (c) 2012-2014 http://www.eryansky.com
 * <p/>
 * Licensed under the Apache License, Version 2.0 (the "License");
 */
public interface INotice {

    String getTitle();
    String getType();
    String getTypeView();
    String getContent();
    String getPublishUserName();
    String getPublishOrganName();
    Date getPublishTime();
    Integer getIsTop();
    String getIsTopView();
    String getNoticeModeView();
}

src/main/webapp/WEB-INF/views/modules/sys/bug-import.jsp
<%@ page language="java" pageEncoding="UTF-8" contentType="text/html; charset=UTF-8"%>
<%@ include file="/common/taglibs.jsp"%>
<script type="text/javascript">
</script>
<div>
	<form id="bug_import_form" class="dialog-form" enctype="multipart/form-data" method="post" novalidate>
        <div>
			<label>上传文件:</label>
		    <input id="filedata" name="filedata" type="file" >
		</div>
	</form>
</div>

src/main/webapp/WEB-INF/views/modules/sys/bug-view.jsp
<%@ page language="java" pageEncoding="UTF-8" contentType="text/html; charset=UTF-8"%>
<%@ include file="/common/taglibs.jsp"%>
<div>
	<div align="center">
	    <h3 style="color:${model.color} ">${model.title}</h3>
	</div>
	<div align="right">
	   [ ${model.createUser} 发布于<fmt:formatDate value="${model.createTime}" type="both" /> ]
	</div>
	<hr>
	<div>${model.content}</div>
</div>

src/main/webapp/WEB-INF/views/modules/sys/organ-input.jsp
<%@ page language="java" pageEncoding="UTF-8" contentType="text/html; charset=UTF-8"%>
<%@ include file="/common/taglibs.jsp"%>
<script type="text/javascript">
    var organType_combobox;
    var $_parent_combotree;
    var organTypeUrl = '${ctxAdmin}/sys/organ/organTypeCombobox?selectType=select';
    $(function() {
        loadParent();
        loadType();
        if("${model.id}"==""){  //新增
            setSortValue();
            $("input[name=status]:eq(0)").attr("checked",'checked');//状态 初始化值
        }
    });
    //加载父级机构
    function loadParent(){
        $_parent_combotree = $('#_parentId').combotree({
            url:'${ctxAdmin}/sys/organ/parentOrgan?selectType=select',
            multiple:false,//是否可多选
            editable:false,//是否可编辑
            height:28,
            width:120,
            valueField:'id',
            onHidePanel:function(){
                //防止自关联
                if($('#id').val() && $(this).combotree('getValue') == $('#id').val()){
                    eu.showMsg('不允许设置上级机构为自己,请重新选择!');
                    $(this).combotree('setValue','');
                }
            },
            onBeforeLoad:function(node,param){
                param.id = "${model.id}";
            },
            onSelect:function(node){
                //上级机构类型 机构：0 部门：1  小组：2
                var parentType = node.attributes.type;
                if(parentType != undefined){
                    organType_combobox.combobox('reload',organTypeUrl+"&parentOrganType="+parentType);
                }
            }

        });
    }

    //加载机构类型
    function loadType(){
        organType_combobox = $('#type').combobox({
            url:organTypeUrl+"&parentOrganType=${parentOrganType}",
            multiple:false,//是否可多选
            editable:false,//是否可编辑
            height:28,
            width:120,
            <%--disabled:${hasChild},--%>
            validType:['comboboxRequired[\'#type\']']
        });
    }

    //设置排序默认值
    function setSortValue() {
        $.get('${ctxAdmin}/sys/organ/maxSort', function(data) {
            if (data.code == 1) {
                $('#orderNo').numberspinner('setValue',data.obj+1);
            }
        }, 'json');
    }
</script>
<div>
    <form id="organ_form" class="dialog-form" method="post">
        <input type="hidden" id="id" name="id" />
        <!-- 用户版本控制字段 version -->
        <input type="hidden" id="version" name="version" />
        <div>
            <label>上级机构:</label>
            <input id="_parentId" name="_parentId" />
        </div>
        <div>
            <label>机构类型:</label>
            <input id="type" name="type" data-options="required:true,missingMessage:'请选择机构类型.'" />
            <%--提示小图标--%>
            <span class="tree-icon tree-file easyui-icon-tip easyui-tooltip"
                  title="顶级机构只能为[机构(法人单位)]；上级机构的机构类型为[部门]，则机构类型只可以为[部门]或者[小组]；上级机构的机构类型为[小组]，则机构类型只可以为[小组]." ></span>
        </div>
        <div>
            <label>机构名称:</label>
            <input type="text" id="name" name="name"
                   maxLength="255" class="easyui-validatebox textbox" placeholder="请输入机构名称..."
                   data-options="required:true,missingMessage:'请输入机构名称.',validType:['minLength[1]']" />
        </div>
        <div>
            <label>机构系统编码:</label>
            <input type="text" id="sysCode" name="sysCode"
                   maxLength="36" class="easyui-validatebox textbox" placeholder="请输入机构系统编码..."
                   data-options="required:true,missingMessage:'请输入机构系统编码.',validType:['minLength[1]']" />
        </div>
        <div>
            <label>机构编码:</label>
            <input type="text" id="code" name="code"
                   maxLength="36" class="easyui-validatebox textbox" placeholder="请输入机构编码..."
                   data-options="validType:['minLength[1]']" />
        </div>
        <div>
            <label>地址:</label>
            <input type="text" id="address" name="address"
                   maxLength="255" class="easyui-validatebox textbox" placeholder="请输入地址..."
                   data-options="validType:['minLength[1]']" />
        </div>
        <div>
            <label>电话号码:</label>
            <input type="text" id="phone" name="phone"
                   class="easyui-validatebox textbox" placeholder="请输入地址..."
                   data-options="validType:['phone']" />
        </div>
        <div>
            <label>传真:</label>
            <input type="text" id="fax" name="fax"
                   class="easyui-validatebox textbox" placeholder="请输入传真..."/>
        </div>
        <div>
            <label>排序:</label>
            <input type="text" id="orderNo" name="orderNo" class="easyui-numberspinner" STYLE="width: 120px;"
                   data-options="min:1,max:99999999,size:9,maxlength:9,height:28" />
        </div>
        <div>
            <label>状态:</label>
            <input type="radio" name="status" style="width: 20px;" value="0" /> 启用
            <input type="radio" name="status" style="width: 20px;" value="3" /> 停用
        </div>
    </form>
</div>

src/main/webapp/WEB-INF/views/modules/sys/role-input.jsp
<%@ page language="java" pageEncoding="UTF-8" contentType="text/html; charset=UTF-8"%>
<%@ include file="/common/taglibs.jsp"%>
<script type="text/javascript">
</script>
<div>
    <form id="role_form" class="dialog-form" method="post" novalidate>
        <input type="hidden"  name="id" />
        <!-- 用户版本控制字段 version -->
        <input type="hidden" id="version" name="version" />
        <div>
            <label>角色名称:</label>
            <input name="name" type="text" class="easyui-validatebox textbox"
                   maxLength="100" data-options="required:true,missingMessage:'请输入角色名称.',validType:['minLength[1]','legalInput']">
        </div>
        <div>
            <label>角色编码:</label>
            <input name="code" type="text" class="easyui-validatebox textbox"
                   maxLength="36" >
        </div>
        <div>
            <label style="vertical-align: top;">描述:</label>
            <%--<textarea maxLength="255" name="remark"--%>
                      <%--style="position: relative; resize: none; height: 100px; width: 260px;"></textarea>--%>
            <input name="remark" class="easyui-textbox" data-options="multiline:true" style="width:260px;height:100px;">
        </div>
    </form>
</div>

src/main/webapp/WEB-INF/views/modules/sys/role.jsp
<%@ page contentType="text/html;charset=UTF-8"%>
<%@ include file="/common/taglibs.jsp"%>
<%@ include file="/common/meta.jsp"%>
<link href="${ctxStatic}/js/kendoui/styles/kendo.common.min.css" rel="stylesheet">
<link href="${ctxStatic}/js/kendoui/styles/kendo.default.min.css" rel="stylesheet">
<script src="${ctxStatic}/js/kendoui/js/kendo.all.min.js"></script>
<script src="${ctxStatic}/js/easyui-${ev}/datagridview/datagrid-bufferview.js"></script>
<script type="text/javascript" src="${ctxStatic}/app/modules/sys/role.js?_=${sysInitTime}" charset="utf-8"></script>
<%-- 列表右键 --%>
<div id="role_datagrid_menu" class="easyui-menu" style="width:120px;display: none;">
	<div onclick="showDialog();" data-options="iconCls:'easyui-icon-add'">新增</div>
	<div onclick="edit();" data-options="iconCls:'easyui-icon-edit'">编辑</div>
	<div onclick="del();" data-options="iconCls:'easyui-icon-remove'">删除</div>
    <div onclick="editRoleResource();" data-options="iconCls:'eu-icon-folder'">设置资源</div>
    <div onclick="editRoleUser();" data-options="iconCls:'eu-icon-user'">设置用户</div>
</div>

<div class="easyui-layout" fit="true" style="margin: 0px;border: 0px;overflow: hidden;width:100%;height:100%;">
    <div data-options="region:'north',title:'过滤条件',collapsed:false,split:false,border:false"
         style="padding: 0px; height: 70px;width:100%; overflow-y: hidden;">
        <form id="role_search_form" style="padding: 5px;">
            &nbsp;角色名称: &nbsp;<input type="text" class="easyui-validatebox textbox eu-input" name="filter_LIKES_name" placeholder="请输入角色名称..."
                              onkeydown="if(event.keyCode==13)search()"  maxLength="25" style="width: 160px" />
            &nbsp;<a class="easyui-linkbutton" href="#" data-options="iconCls:'easyui-icon-search',width:100,height:28,onClick:search">查询</a>
            <a class="easyui-linkbutton" href="#" data-options="iconCls:'easyui-icon-no',width:100,height:28" onclick="javascript:$role_search_form.form('reset');">重置查询</a>
        </form>
    </div>
    <%-- 中间部分 列表 --%>
    <div data-options="region:'center',split:false,border:false"
         style="padding: 0px; height: 100%;width:100%; overflow-y: hidden;">
        <table id="role_datagrid"></table>
    </div>
</div>


   

src/main/webapp/WEB-INF/views/modules/sys/user-password.jsp
<%@ page language="java" pageEncoding="UTF-8" contentType="text/html; charset=UTF-8"%>
<div>
	<form id="user_password_form" class="dialog-form" method="post">
		<input type="hidden" id="user_password_form_id" name="id" /> 
		<div>
			<label>新密码:</label> 
			<input type="password" id="newPassword" name="newPassword"
				class="easyui-validatebox textbox" required="true" missingMessage="请输入新密码."
				validType="minLength[1]" />
		</div>
		<div>
			<label>确认新密码:</label> 
			<input type="password" id="newPassword2" name="newPassword2"
				class="easyui-validatebox textbox" required="true"
				missingMessage="请再次输入新密码." validType="equalTo['#newPassword']"
				invalidMessage="两次输入密码不匹配." />
		</div>
	</form>
</div>